# Generated by Django 5.1.5 on 2025-02-13 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernumber',
            name='pdf1',
            field=models.FileField(blank=True, null=True, upload_to='userfolder/'),
        ),
        migrations.AddField(
            model_name='usernumber',
            name='pdf2',
            field=models.FileField(blank=True, null=True, upload_to='userfolder/'),
        ),
        migrations.AddField(
            model_name='usernumber',
            name='pdf3',
            field=models.FileField(blank=True, null=True, upload_to='userfolder/'),
        ),
    ]
